declare module '*.png'

declare module 'react-parallax'
declare module 'pluralize'
declare module 'url-join'
declare module 'jdenticon'
declare module 'react-syntax-highlighter/prism'
declare module 'react-mathjax'
declare module 'x-data-spreadsheet'
declare module 'react-color'
declare module 'react-trello'
declare module 'bugsnag-react'
declare module 'toml-j0.4'
declare module 'tomlify-j0.4'
declare module '@terebentina/react-popover'
declare module 'overlayscrollbars'
