const CLONE_REPO = 'CLONE_REPO';
const CHECKPOINT_REPO = 'CHECKPOINT_REPO';
const PULL_REPO = 'PULL_REPO';
const GET_DIFF = 'GET_DIFF';
const REVERT_FILES = 'REVERT_FILES';

module.exports = {
    CLONE_REPO,
    CHECKPOINT_REPO,
    PULL_REPO,
    GET_DIFF,
    REVERT_FILES,
};
